### ISSUE TITLE
API Design: Differentiate between `Token` and `SignedToken`

### ISSUE THREAD

**Issue by vbrandl** [mikkyang/rust-jwt#19]
Hi there,

I don't know if you are open to suggestion for your API design, so if not, just close this issue.

The `Token` type exposes a `parse` function to parse strings into unverified `Token`s. The `verify` function on token returns only a boolean for verification and all claims can be accessed directly from the `Token` type. In most cases it would be incorrect and might even lead to security flaws, if the claims where used before verifying the token. The current API design allows for these kinds of bugs to happen.

Here is my proposal:

* `Token::parse` stays as is and returns a `Result<Token, Error>`
* Introduce a new type `VerifiedToken` to represent tokens after verification
* `Token::verify` returns `Result<VerifiedToken, VerificationError>` or `Option<VerifiedToken>`
* Only for `VerifiedToken`, the `claims` field is publicly accessible
* For the rare cases where you need to access the claims of an unverified token, there can be a `Token::claim` function, that is either marked `unsafe` or if that's too much, call it `claim_unverified`, `claim_unsafe`, ...

This change might prevent some logic bugs at the typelevel while not loosing any existing functionality.

If you are open to a change like this, I'd be happy to start working on a PR.

**Comment by mikkyang** [comment]
Thanks for your thoughts! You're right that the current API design isn't ideal. It was written without much thought initially. At the moment, I was thinking that I would make the signature portion a type of its own.

Instead of `Token<H, C>` for just typed headers and claims, it would be `Token<H, C, S>` with the `S` parameter for the signature, conforming to a `Signature` trait. This trait could have various implementations:

* `Unsigned` for tokens that the user is in the process of creating
* `Signed(String)` for tokens the user is done with handling
* `Unverified(&'str)` for tokens the user receives and parses the header and claims but for some reason wants to verify later or is fine without verifying
* `Verified` for tokens the user receives and successfully verifies

The functions could then be modified to be something along the lines of:
`Token::parse` then returns `Result<Token<H, C, Unverified>>`
`Token<H, C, Unverified>::verify` returns a `Result<Token<H, C, Verified>>`

You bring up good points about how certain functions should be limited to verified tokens. For this, implementations could vary based on the signature type, so that only claims are accessible on verified tokens, and writing to a string can only be done on signed tokens, etc, etc.

What are your thoughts on that?

**Comment by vbrandl** [comment]
I think your approach works as well. For restricted access to fields, you just
```
impl Token<H, C, Verified> {
  fn claims(&self) -> Claims {
    ...
  }
```

And for developer ergonomics, there can be a `type VerifiedToken<H, C> = Token<H, C, Verified>` and so on.

**Comment by mikkyang** [comment]
@vbrandl I merged in the changes, and would appreciate your thoughts on the actual usage.

I tried the separate typing but it ended up being more verbose than just importing the type. I'll close this out for now.
